function AnchorMeasure()
n_variance = [1e-2; 1e-1; 1e0; 1e1; 1e2];
iteration = 1e4;
num_sample = 11;
Anchor = struct(...
    'a1',[0;10],...
    'a2',[0;0],...
    'a3',[10;0],...
    'a4',[10;10]...
    );

LSE = struct(...
    'var001',zeros(2,iteration,num_sample),...
    'var01',zeros(2,iteration,num_sample),...
    'var1',zeros(2,iteration,num_sample),...
    'var10',zeros(2,iteration,num_sample),...
    'var100',zeros(2,iteration,num_sample)...
    );

for iter = 1:iteration
    for num = 1:num_sample
        exactPos = [num-1;num-1];
        
        meas_dn_001(:,1) = ...
            [...
            norm(exactPos-Anchor.a1)+sqrt(n_variance(1,1))*randn...
            norm(exactPos-Anchor.a2)+sqrt(n_variance(1,1))*randn...
            norm(exactPos-Anchor.a3)+sqrt(n_variance(1,1))*randn...
            norm(exactPos-Anchor.a4)+sqrt(n_variance(1,1))*randn
            ];
        
        meas_dn_01(:,1) = ...
            [...
            norm(exactPos-Anchor.a1)+sqrt(n_variance(2,1))*randn...
            norm(exactPos-Anchor.a2)+sqrt(n_variance(2,1))*randn...
            norm(exactPos-Anchor.a3)+sqrt(n_variance(2,1))*randn...
            norm(exactPos-Anchor.a4)+sqrt(n_variance(2,1))*randn
            ];
        
        meas_dn_1(:,1) = ...
            [...
            norm(exactPos-Anchor.a1)+sqrt(n_variance(3,1))*randn...
            norm(exactPos-Anchor.a2)+sqrt(n_variance(3,1))*randn...
            norm(exactPos-Anchor.a3)+sqrt(n_variance(3,1))*randn...
            norm(exactPos-Anchor.a4)+sqrt(n_variance(3,1))*randn
            ];
        
        meas_dn_10(:,1) = ...
            [...
            norm(exactPos-Anchor.a1)+sqrt(n_variance(4,1))*randn...
            norm(exactPos-Anchor.a2)+sqrt(n_variance(4,1))*randn...
            norm(exactPos-Anchor.a3)+sqrt(n_variance(4,1))*randn...
            norm(exactPos-Anchor.a4)+sqrt(n_variance(4,1))*randn
            ];
        
        meas_dn_100(:,1) = ...
            [...
            norm(exactPos-Anchor.a1)+sqrt(n_variance(5))*randn,...
            norm(exactPos-Anchor.a2)+sqrt(n_variance(5))*randn,...
            norm(exactPos-Anchor.a3)+sqrt(n_variance(5))*randn,...
            norm(exactPos-Anchor.a4)+sqrt(n_variance(5))*randn
            ];
        
        LSE.var001(:,iter,num) = ToA(meas_dn_001);
        LSE.var01(:,iter,num) = ToA(meas_dn_01);
        LSE.var1(:,iter,num) = ToA(meas_dn_1);
        LSE.var10(:,iter,num) = ToA(meas_dn_10);
        LSE.var100(:,iter,num) = ToA(meas_dn_100);
    end
end
save('ToA.mat','LSE');
end